version: "3.7"
services:
  server:
    build: .
    ports:
     - "80:5000"
    environment:
      - APP_SETTINGS=config.test
      - AWS_ACCESS_KEY=accessKey1
      - AWS_SECRET_KEY=verySecretKey1
      - AWS_REGION=eu-central-1
      - S3_BUCKET=images
      - S3_ENDPOINT=http://s3server:8000
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    links:
      - dynamodb
      - s3server
    depends_on:
      - dynamodb
      - s3server
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8000:8000"
  s3server:
    image: scality/s3server
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=verySecretKey1
    ports:
     - "8008:8000"
  aws-cli:
    image: garland/aws-cli-docker
    environment:
      - AWS_ACCESS_KEY_ID=accessKey1
      - AWS_SECRET_ACCESS_KEY=verySecretKey1
      - AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      - s3server
    command: >
      /bin/sh -c "
        aws s3api create-bucket \
          --bucket images \
          --acl public-read \
          --endpoint http://s3server:8000;
      "
    links:
      - s3server
