version: "3.7"
services:
  server:
    build: .
    ports:
     - "80:5000"
    environment:
      - APP_SETTINGS=config.dev
      - AWS_ACCESS_KEY=accessKey1
      - AWS_SECRET_KEY=verySecretKey1
      - AWS_REGION=eu-central-1
      - S3_BUCKET=images
      - S3_ENDPOINT=http://s3server:8000
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    links:
      - dynamodb
      - s3server
    depends_on:
      - dynamodb
      - s3server
  dynamodb:
    image: amazon/dynamodb-local
    ports:
     - "8000:8000"
  s3server:
    image: scality/s3server
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=verySecretKey1
    ports:
     - "8008:8000"
  aws-cli:
    image: mesosphere/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=accessKey1
      - AWS_SECRET_ACCESS_KEY=verySecretKey1
    depends_on:
      - s3server
    command: s3 mb --endpoint-url=http://s3server:8000 s3://images
    links:
      - s3server
