apiVersion: v1
kind: Service
metadata:
{{- if .Values.imagefetcher.service.annotations }}
  annotations:
{{ toYaml .Values.imagefetcher.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "imagefetcher.name" . }}
    chart: {{ template "imagefetcher.chart" . }}
    component: "{{ .Values.imagefetcher.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "imagefetcher.app.fullname" . }}-api
spec:
{{- if .Values.imagefetcher.service.clusterIP }}
  clusterIP: {{ .Values.imagefetcher.service.clusterIP }}
{{- end }}
{{- if .Values.imagefetcher.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.imagefetcher.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.imagefetcher.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.imagefetcher.service.loadBalancerIP }}
{{- end }}
{{- if .Values.imagefetcher.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.imagefetcher.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
  - name: api
    port: {{ .Values.imagefetcher.service.apiPort }}
    targetPort: api
  selector:
    app: {{ template "imagefetcher.name" . }}
    component: "{{ .Values.imagefetcher.name }}"
    release: {{ .Release.Name }}
  type: {{ .Values.imagefetcher.service.type }}
