ingress:
  domain: test.imagefetcher.com

imagefetcher:
  name: imagefetcher
  node_env: test

  image:
    repository: ""
    tag: latest
    pullPolicy: Always

  replicaCount: 1
  minAvailable: 1

  service:
    annotations: {}
    type: NodePort
    apiPort: 80

  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  s3:
    bucket: ""

  dynamodb:
    endpoint: ""

  affinity: {}

  tolerations: []

  nodeSelector: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
